import type {OllamaChatModelId} from './ollama-chat-settings.js';

export type OllamaImageModelId =
  | 'all-minilm'
  | 'all-minilm:22m'
  | 'all-minilm:22m-l6-v2-fp16'
  | 'all-minilm:33m'
  | 'all-minilm:33m-l12-v2-fp16'
  | 'all-minilm:l12'
  | 'all-minilm:l12-v2'
  | 'all-minilm:l6'
  | 'all-minilm:l6-v2'
  | 'all-minilm:latest'
  | 'all-minilm:v2'
  | 'bge-large'
  | 'bge-large:335m'
  | 'bge-large:335m-en-v1.5-fp16'
  | 'bge-large:latest'
  | 'bge-m3'
  | 'bge-m3:567m'
  | 'bge-m3:567m-fp16'
  | 'bge-m3:latest'
  | 'granite-embedding'
  | 'granite-embedding:278m'
  | 'granite-embedding:278m-fp16'
  | 'granite-embedding:30m'
  | 'granite-embedding:30m-en'
  | 'granite-embedding:30m-en-fp16'
  | 'granite-embedding:latest'
  | 'mxbai-embed-large'
  | 'mxbai-embed-large:335m'
  | 'mxbai-embed-large:335m-v1-fp16'
  | 'mxbai-embed-large:latest'
  | 'mxbai-embed-large:v1'
  | 'nomic-embed-text'
  | 'nomic-embed-text:137m-v1.5-fp16'
  | 'nomic-embed-text:latest'
  | 'nomic-embed-text:v1.5'
  | 'paraphrase-multilingual'
  | 'paraphrase-multilingual:278m'
  | 'paraphrase-multilingual:278m-mpnet-base-v2-fp16'
  | 'paraphrase-multilingual:latest'
  | 'snowflake-arctic-embed'
  | 'snowflake-arctic-embed2'
  | 'snowflake-arctic-embed2:568m'
  | 'snowflake-arctic-embed2:568m-l-fp16'
  | 'snowflake-arctic-embed2:latest'
  | 'snowflake-arctic-embed:110m'
  | 'snowflake-arctic-embed:110m-m-fp16'
  | 'snowflake-arctic-embed:137m'
  | 'snowflake-arctic-embed:137m-m-long-fp16'
  | 'snowflake-arctic-embed:22m'
  | 'snowflake-arctic-embed:22m-xs-fp16'
  | 'snowflake-arctic-embed:335m'
  | 'snowflake-arctic-embed:335m-l-fp16'
  | 'snowflake-arctic-embed:33m'
  | 'snowflake-arctic-embed:33m-s-fp16'
  | 'snowflake-arctic-embed:l'
  | 'snowflake-arctic-embed:latest'
  | 'snowflake-arctic-embed:m'
  | 'snowflake-arctic-embed:m-long'
  | 'snowflake-arctic-embed:s'
  | 'snowflake-arctic-embed:xs'
  | OllamaChatModelId
  | (string & NonNullable<unknown>);

export interface OllamaImageSettings {
  maxImagesPerCall?: number;
}
